name: todo
description: Todo list
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  gap: ^3.0.0
  google_fonts: ^6.2.0
  infinite_listview: ^1.1.0
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.0.0
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.0.0
  riverpod: ^2.6.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/